//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EXISTS => ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_EMAIL => ResourceManager.GetString("INVALID_EMAIL", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_PASSWORD => ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NAME_EMPTY => ResourceManager.GetString("NAME_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string SEE_ERRORS => ResourceManager.GetString("SEE_ERRORS", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string UNKNOWN_ERROR => ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string VALIDATION_FAILED => ResourceManager.GetString("VALIDATION_FAILED", resourceCulture);

	}
}